# Generated by Django 6.0.7 on 2026-07-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(default='স্নিগ্ধ জ্ঞানের আলো বিদ্যাপীঠ', max_length=255)),
                ('name_en', models.CharField(default='SNIGDHA GYANER ALO VIDYAPITH', max_length=255)),
                ('address_bn', models.CharField(default='গাইবান্ধা সদর, জেলা: গাইবান্ধা', max_length=255)),
                ('established_year', models.CharField(default='২০১৪ইং', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=50)),
                ('token_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('exam_year', models.CharField(max_length=10)),
                ('gpa', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
