# Generated by Django 6.0.7 on 2026-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_testimonial_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='testimonial_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
