# Generated by Django 6.0.7 on 2026-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_student_is_testimonial_printed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='শ্রেণী'),
        ),
    ]
