# Generated by Django 6.0.7 on 2026-07-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=255, verbose_name='প্রতিষ্ঠানের নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=255, verbose_name='প্রতিষ্ঠানের নাম (ইংরেজি)')),
                ('eiin', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('controller_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('serial_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('roll_no', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50, verbose_name='শ্রেণী')),
                ('session', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('examinee_type', models.CharField(default='REGULAR', max_length=50)),
                ('subjects', models.ManyToManyField(to='admit_cards.subject')),
            ],
        ),
    ]
