# Generated by Django 6.0.7 on 2026-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ঠিকানা'),
        ),
    ]
