# Generated by Django 6.0.7 on 2026-07-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('BANGLA', 'বাংলা'), ('ENGLISH', 'ইংরেজি'), ('MATH', 'গণিত'), ('SCIENCE', 'বিজ্ঞান')], max_length=20)),
                ('question_type', models.CharField(choices=[('MCQ', 'বহুনির্বাচনী (MCQ)'), ('CREATIVE', 'সৃজনশীল / রচনামূলক'), ('SHORT', 'সংক্ষিপ্ত প্রশ্ন'), ('FILL_BLANK', 'শূন্যস্থান পূরণ')], max_length=20)),
                ('class_level', models.IntegerField(default=6)),
                ('marks', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_type', models.CharField(choices=[('ALGEBRA', 'বীজগণিত'), ('GEOMETRY', 'জ্যামিতি'), ('ARITHMETIC', 'পাটিগণিত')], max_length=20)),
                ('latex_formula', models.TextField(help_text='Math equations using LaTeX or standard text')),
                ('has_diagram', models.BooleanField(default=False)),
                ('diagram_image', models.ImageField(blank=True, null=True, upload_to='math_diagrams/')),
                ('base_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='math_detail', to='academics.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('SEEN', 'Seen Passage'), ('UNSEEN', 'Unseen Passage'), ('GRAMMAR', 'Grammar'), ('WRITING', 'Writing')], max_length=20)),
                ('passage', models.TextField(blank=True, help_text='Comprehension Passage', null=True)),
                ('question_text', models.TextField()),
                ('base_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='english_detail', to='academics.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='BanglaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('PROSE', 'গদ্য'), ('POETRY', 'পদ্য'), ('GRAMMAR', 'ব্যাকরণ')], max_length=20)),
                ('passage', models.TextField(blank=True, help_text='উদ্দীপক / অনুচ্ছেদ', null=True)),
                ('question_text', models.TextField(help_text='মূল প্রশ্ন')),
                ('base_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bangla_detail', to='academics.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='ScienceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('PHYSICS', 'পদার্থ'), ('CHEMISTRY', 'রসায়ন'), ('BIOLOGY', 'জীববিজ্ঞান'), ('GENERAL', 'সাধারণ')], max_length=20)),
                ('stem_text', models.TextField(help_text='উদ্দীপক / পরীক্ষা বিবরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='science_diagrams/')),
                ('question_text', models.TextField()),
                ('base_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='science_detail', to='academics.questionbank')),
            ],
        ),
    ]
