# Generated by Django 6.0.7 on 2026-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('student_name_en', models.CharField(max_length=100)),
                ('student_name_bn', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2026', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
