# Generated by Django 6.0.7 on 2026-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentadmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmission',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='student_class',
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='birth_reg_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='জন্ম নিবন্ধন নম্বর / Birth Reg No'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='desired_class',
            field=models.CharField(default='Class 6', max_length=50, verbose_name='শ্রেণী / Desired Class'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='জন্ম তারিখ / Date of Birth'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='father_nid',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='পিতার এনআইডি / Father NID'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='gender',
            field=models.CharField(choices=[('Boy', 'ছেলে'), ('Girl', 'মেয়ে'), ('Other', 'অন্যান্য')], default='Boy', max_length=20, verbose_name='লিঙ্গ / Gender'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='অভিভাবকের নাম / Guardian Name'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='guardian_nid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='অভিভাবকের এনআইডি / Guardian NID'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='মোবাইল নম্বর / Mobile'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='mother_nid',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='মাতার এনআইডি / Mother NID'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='permanent_address_detail',
            field=models.TextField(blank=True, default='', verbose_name='বিস্তারিত ঠিকানা / Address Line'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='permanent_district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='জেলা / District'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='permanent_division',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='বিভাগ / Division'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='permanent_post_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='পোস্ট কোড / Post Code'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='permanent_upazila',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='উপজেলা/থানা / Upazila'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='present_address_detail',
            field=models.TextField(blank=True, default='', verbose_name='বিস্তারিত ঠিকানা / Address Line'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='present_district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='জেলা / District'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='present_division',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='বিভাগ / Division'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='present_post_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='পোস্ট কোড / Post Code'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='present_upazila',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='উপজেলা/থানা / Upazila'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='re_mobile',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='মোবাইল নম্বর নিশ্চিত করুন'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'অপেক্ষমাণ / Pending'), ('Approved', 'অনুমোদিত / Approved')], default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='version',
            field=models.CharField(choices=[('Bangla', 'বাংলা ভার্সন'), ('English', 'English Version')], default='Bangla', max_length=20, verbose_name='ভার্সন / Version'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='academic_year',
            field=models.CharField(blank=True, default='2026', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='admission_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="পিতার নাম / Father's Name"),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="মাতার নাম / Mother's Name"),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='ছবি / Photo'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='section',
            field=models.CharField(blank=True, default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='student_name_bn',
            field=models.CharField(max_length=200, verbose_name='নাম (বাংলা)'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='student_name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (English)'),
        ),
    ]
