# Generated by Django 6.0.7 on 2026-07-22 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_from', models.IntegerField()),
                ('mark_to', models.IntegerField()),
                ('letter_grade', models.CharField(max_length=5)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('remarks', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-mark_from'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='GOVT. HIGH SCHOOL, NARAYANGANJ', max_length=255)),
                ('name_bn', models.CharField(default='সরকারি উচ্চ বিদ্যালয়, নারায়ণগঞ্জ', max_length=255)),
                ('eiin', models.CharField(default='100184', max_length=20)),
                ('board_or_authority', models.CharField(default='Directorate of Secondary and Higher Education', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution/')),
                ('principal_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('controller_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('roll_no', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('session', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('exam_name', models.CharField(default='J.S.C / S.S.C Examination', max_length=100)),
                ('group_or_subject', models.CharField(default='Science', max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=150)),
                ('total_credit_or_marks', models.IntegerField(default=100)),
                ('obtained_marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='transcripts.student')),
            ],
        ),
    ]
