from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('BANGLA_1', 'বাংলা ১ম পত্র'), ('BANGLA_2', 'বাংলা ২য় পত্র'), ('ENGLISH_1', 'English First Paper'), ('ENGLISH_2', 'English Second Paper'), ('MATH', 'গণিত'), ('SCIENCE', 'সাধারণ বিজ্ঞান'), ('PHYSICS', 'পদার্থবিজ্ঞান'), ('CHEMISTRY', 'রসায়ন'), ('HIGHER_MATH', 'উচ্চতর গণিত'), ('ICT', 'তথ্য ও যোগাযোগ প্রযুক্তি (ICT)')], max_length=30)),
                ('class_level', models.CharField(choices=[('Class 6', '৬ষ্ঠ শ্রেণি'), ('Class 7', '৭ম শ্রেণি'), ('Class 8', '৮ম শ্রেণি'), ('Class 9', '৯ম শ্রেণি'), ('Class 10', '১০ম শ্রেণি'), ('SSC', 'এসএসসি (SSC)'), ('Class 11', 'একাদশ শ্রেণি'), ('Class 12', 'দ্বাদশ শ্রেণি'), ('HSC', 'এইচএসসি (HSC)')], default='Class 9', max_length=20)),
                ('chapter_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255, verbose_name='অধ্যায়ের নাম')),
                ('description', models.TextField(blank=True, null=True, verbose_name='সংক্ষিপ্ত বিবরণ')),
                ('topics_json', models.JSONField(blank=True, default=list, help_text='টপিক সমূহের তালিকা (List of topics)')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Completion percentage 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['class_level', 'subject', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPaperTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('BOARD', 'Board Style (NCTB Official)'), ('SCHOOL', 'School Standard Style'), ('MODERN', 'Modern Dynamic Style'), ('MADRASAH', 'Madrasah Board Style'), ('COLLEGE', 'College / Higher Secondary'), ('CUSTOM', 'Custom User Template')], default='BOARD', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('style_config_json', models.JSONField(blank=True, default=dict, help_text='Font size, margins, grid columns settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='বার্ষিক পরীক্ষা — ২০২৬', max_length=255, verbose_name='প্রশ্নপত্রের শিরোনাম / Exam Name')),
                ('academic_year', models.CharField(default='2026', max_length=10)),
                ('class_name', models.CharField(default='Class 9', max_length=50)),
                ('section', models.CharField(blank=True, default='A', max_length=50)),
                ('subject', models.CharField(default='গণিত', max_length=50)),
                ('teacher_name', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('time_allowed', models.CharField(default='৩ ঘণ্টা', max_length=100, verbose_name='পরীক্ষার সময়')),
                ('full_marks', models.PositiveIntegerField(default=100)),
                ('pass_marks', models.PositiveIntegerField(default=33)),
                ('written_marks', models.PositiveIntegerField(default=70)),
                ('mcq_marks', models.PositiveIntegerField(default=30)),
                ('creative_marks', models.PositiveIntegerField(default=70)),
                ('school_name', models.CharField(default='গাজীমাহমুদ নিম্ন মাধ্যমিক বিদ্যালয়', max_length=255)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('eiin_number', models.CharField(blank=True, default='EIIN: 123456', max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(default='১. সকল প্রশ্নের মান সমান。\n২. প্রয়োজনীয় ক্ষেত্রে ডান পার্শ্বের সংখ্যা প্রশ্নের পূর্ণমান জ্ঞাপন করে।\n৩. ক্যালকুলেটর ব্যবহার অনুমোদিত।')),
                ('prepared_by', models.CharField(default='বিষয় শিক্ষক', max_length=100)),
                ('verified_by', models.CharField(default='পরীক্ষা নিয়ন্ত্রক', max_length=100)),
                ('approved_by', models.CharField(default='প্রধান শিক্ষক', max_length=100)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('questions_json', models.JSONField(default=list, help_text='Ordered array of question objects, custom marks, numbers')),
                ('numbering_style', models.CharField(choices=[('BANGLA', 'Bangla (১, ২, ৩ / ক, খ, গ)'), ('ENGLISH', 'English (1, 2, 3)'), ('ROMAN', 'Roman (i, ii, iii)')], default='BANGLA', max_length=20)),
                ('paper_size', models.CharField(choices=[('A4_PORTRAIT', 'A4 Portrait'), ('A4_LANDSCAPE', 'A4 Landscape'), ('LEGAL', 'Legal'), ('LETTER', 'Letter')], default='A4_PORTRAIT', max_length=20)),
                ('margin_top_mm', models.PositiveIntegerField(default=15)),
                ('margin_bottom_mm', models.PositiveIntegerField(default=15)),
                ('margin_left_mm', models.PositiveIntegerField(default=15)),
                ('margin_right_mm', models.PositiveIntegerField(default=15)),
                ('password_protection', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'খসড়া / Draft'), ('PUBLISHED', 'প্রকাশিত / Published'), ('ARCHIVED', 'আর্কাইভ / Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_paper.questionpapertemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('BANGLA_1', 'বাংলা ১ম পত্র'), ('BANGLA_2', 'বাংলা ২য় পত্র'), ('ENGLISH_1', 'English First Paper'), ('ENGLISH_2', 'English Second Paper'), ('MATH', 'গণিত'), ('SCIENCE', 'সাধারণ বিজ্ঞান'), ('PHYSICS', 'পদার্থবিজ্ঞান'), ('CHEMISTRY', 'রসায়ন'), ('HIGHER_MATH', 'উচ্চতর গণিত'), ('ICT', 'তথ্য ও যোগাযোগ প্রযুক্তি (ICT)')], max_length=30)),
                ('class_level', models.CharField(choices=[('Class 6', '৬ষ্ঠ শ্রেণি'), ('Class 7', '৭ম শ্রেণি'), ('Class 8', '৮ম শ্রেণি'), ('Class 9', '৯ম শ্রেণি'), ('Class 10', '১০ম শ্রেণি'), ('SSC', 'এসএসসি (SSC)'), ('Class 11', 'একাদশ শ্রেণি'), ('Class 12', 'দ্বাদশ শ্রেণি'), ('HSC', 'এইচএসসি (HSC)')], default='Class 9', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=250, null=True)),
                ('question_type', models.CharField(choices=[('CREATIVE', 'সৃজনশীল (CQ)'), ('MCQ', 'বহুনির্বাচনী (MCQ)'), ('SHORT', 'সংক্ষিপ্ত প্রশ্ন'), ('ESSAY', 'রচনামূলক প্রশ্ন'), ('PRACTICAL', 'ব্যবহারিক প্রশ্ন'), ('DIAGRAM', 'চিত্রভিত্তিক প্রশ্ন'), ('NUMERICAL', 'গাণিতিক সমস্যা')], default='CREATIVE', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'সহজ (Easy)'), ('MEDIUM', 'মধ্যম (Medium)'), ('HARD', 'কঠিন (Hard)')], default='MEDIUM', max_length=10)),
                ('board_standard', models.CharField(blank=True, choices=[('DHAKA', 'ঢাকা বোর্ড'), ('RAJSHAHI', 'রাজশাহী বোর্ড'), ('KHULNA', 'খুলনা বোর্ড'), ('BARISAL', 'বরিশাল বোর্ড'), ('SYLHET', 'সিলেট বোর্ড'), ('COMILLA', 'কুমিল্লা বোর্ড'), ('JESSORE', 'যশোর বোর্ড'), ('DINAJPUR', 'দিনাজপুর বোর্ড'), ('MYMENSINGH', 'ময়মনসিংহ বোর্ড'), ('CHITTAGONG', 'চট্টগ্রাম বোর্ড'), ('MADRASAH', 'মাদ্রাসা বোর্ড'), ('TECHNICAL', 'কারিগরি বোর্ড')], max_length=20, null=True)),
                ('board_year', models.PositiveIntegerField(blank=True, null=True)),
                ('marks', models.PositiveIntegerField(default=10)),
                ('question_text', models.TextField(help_text='Supports MathJax, chemical formulas, HTML tables & code', verbose_name='মূল প্রশ্ন / নির্দেশনা')),
                ('answer_explanation', models.TextField(blank=True, null=True, verbose_name='উত্তর / সমাধান / ব্যাখ্যা')),
                ('stimulus_passage', models.TextField(blank=True, null=True, verbose_name='উদ্দীপক (Stimulus / Passage)')),
                ('stimulus_image', models.ImageField(blank=True, null=True, upload_to='question_stimulus/')),
                ('stimulus_table_data', models.JSONField(blank=True, null=True)),
                ('q_ka', models.TextField(blank=True, null=True, verbose_name='ক নম্বর প্রশ্ন (1 Mark)')),
                ('m_ka', models.PositiveIntegerField(default=1)),
                ('q_kha', models.TextField(blank=True, null=True, verbose_name='খ নম্বর প্রশ্ন (2 Marks)')),
                ('m_kha', models.PositiveIntegerField(default=2)),
                ('q_ga', models.TextField(blank=True, null=True, verbose_name='গ নম্বর প্রশ্ন (3 Marks)')),
                ('m_ga', models.PositiveIntegerField(default=3)),
                ('q_gha', models.TextField(blank=True, null=True, verbose_name='ঘ নম্বর প্রশ্ন (4 Marks)')),
                ('m_gha', models.PositiveIntegerField(default=4)),
                ('option_a', models.CharField(blank=True, max_length=500, null=True, verbose_name='অপশন (ক)')),
                ('option_b', models.CharField(blank=True, max_length=500, null=True, verbose_name='অপশন (খ)')),
                ('option_c', models.CharField(blank=True, max_length=500, null=True, verbose_name='অপশন (গ)')),
                ('option_d', models.CharField(blank=True, max_length=500, null=True, verbose_name='অপশন (ঘ)')),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'ক'), ('B', 'খ'), ('C', 'গ'), ('D', 'ঘ')], max_length=5, null=True)),
                ('negative_mark', models.FloatField(default=0.0)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('latex_formula', models.TextField(blank=True, null=True, verbose_name='LaTeX / MathJax Formula')),
                ('chemical_equation', models.TextField(blank=True, null=True, verbose_name='Chemical Formula / Equation')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='Programming Code Snippet (ICT)')),
                ('diagram_image', models.ImageField(blank=True, null=True, upload_to='question_diagrams/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_paper.chapter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
