# Generated by Django 6.0.7 on 2026-07-20 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Present (Biometric)', 'Present (Biometric)'), ('Absent', 'Absent'), ('Late', 'Late'), ('Personal Leave', 'Personal Leave'), ('Holiday', 'Holiday'), ('Pending', 'Pending')], default='Pending', max_length=25)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Present (Biometric)', 'Present (Biometric)'), ('Absent', 'Absent'), ('Casual Leave', 'Casual Leave'), ('Special Leave', 'Special Leave'), ('Holiday', 'Holiday'), ('Pending', 'Pending')], default='Pending', max_length=25)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
